modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/cakeGit/Create-Trading-Floor/issues"
license = "MIT"

[[mods]]
modId = "trading_floor"
version = "${version}"
displayName = "Create: Trading Floor"
authors = "Tazer & Cak"
description = '''
Automate trading with villagers using create!
'''
logoFile = "icon.png"
displayURL = "https://modrinth.com/mod/create-trading-floor"
updateJSONURL = "https://raw.githubusercontent.com/cakeGit/Create-Trading-Floor/refs/heads/1.20.1/forge_updates.json"

[[dependencies.trading_floor]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trading_floor]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.trading_floor]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"
[[dependencies.trading_floor]]
modId="jei"
mandatory=false
versionRange="${jei_version}"
ordering="NONE"
side="BOTH"